# Generated by Django 3.2.13 on 2022-05-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_product', '0002_auto_20220526_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='gambar',
        ),
    ]
